// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXfSmHcnFUGGS6xFqCvyB_BbHQL26h9q4',
    appId: '1:145448984942:web:8c5af2dfd4637b3679617f',
    messagingSenderId: '145448984942',
    projectId: 'easyshopping-5bc69',
    authDomain: 'easyshopping-5bc69.firebaseapp.com',
    storageBucket: 'easyshopping-5bc69.appspot.com',
    measurementId: 'G-9VXR7SK5PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLgasGipykpw87z2JTeElw4yw3bELJ-ps',
    appId: '1:145448984942:android:59ff59e1516e50a779617f',
    messagingSenderId: '145448984942',
    projectId: 'easyshopping-5bc69',
    storageBucket: 'easyshopping-5bc69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc-JTN3H1B7KBnbpYP33NpVKk-JrbHDO4',
    appId: '1:145448984942:ios:8f5d4669c49cab2279617f',
    messagingSenderId: '145448984942',
    projectId: 'easyshopping-5bc69',
    storageBucket: 'easyshopping-5bc69.appspot.com',
    iosBundleId: 'com.example.vijayho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc-JTN3H1B7KBnbpYP33NpVKk-JrbHDO4',
    appId: '1:145448984942:ios:8f5d4669c49cab2279617f',
    messagingSenderId: '145448984942',
    projectId: 'easyshopping-5bc69',
    storageBucket: 'easyshopping-5bc69.appspot.com',
    iosBundleId: 'com.example.vijayho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXfSmHcnFUGGS6xFqCvyB_BbHQL26h9q4',
    appId: '1:145448984942:web:cf68050bc886ee6a79617f',
    messagingSenderId: '145448984942',
    projectId: 'easyshopping-5bc69',
    authDomain: 'easyshopping-5bc69.firebaseapp.com',
    storageBucket: 'easyshopping-5bc69.appspot.com',
    measurementId: 'G-EMS8PGVW4G',
  );
}
